### ISSUE TITLE
Add a transaction creation form so that a tx with any parameters can be created

### ISSUE THREAD

**Issue by danjm** [MetaMask/test-dapp#128]
It would be good if our test dapp had a form, with fields for each tx parameter, that could be filled in with any arbitrary values.

This should include the ability to set the transaction type (only to `0x0` or `0x2` for now). Appropriate gas fields should be shown for the appropriate type.

**Comment by bschorchit** [comment]
Should this be closed as https://github.com/MetaMask/test-dapp/pull/132 was merged?

**Comment by dragana8** [comment]
@bschorchit I think it should.

**Comment by mcmire** [comment]
Closing issue since #132 was merged.
