### ISSUE TITLE
Improve test-dapp

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/test-dapp#140]
It would be great if a user could control finite tx details (like amounts, gas, etc) as well as be able to generate and manipulate deeplinks. perhaps merging in features from https://github.com/MetaMask/metamask-deeplinks could be useful?

**Comment by danjm** [comment]
This PR addresses controlling finite tx details: https://github.com/MetaMask/test-dapp/pull/132

**Comment by mcmire** [comment]
Is this issue still relevant?

**Comment by rickycodes** [comment]
I think #132 does the trick!
