### ISSUE TITLE
What is bundle.js? It's not in the repo folder.

### ISSUE THREAD

**Issue by psmithson** [MetaMask/test-dapp#191]
I notice the file 
https://metamask.github.io/test-dapp/bundle.js
is loaded at 
https://metamask.github.io/test-dapp/
but is not present in the src directory
https://github.com/MetaMask/test-dapp/tree/main/src

Why is that? I saved a copy of this file as it was served. What is it? Seems like the app won't run locally for me without this. 

Thanks.

**Comment by katopz** [comment]
it's in `dist` folder after build.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/97060/193379124-74aec95c-5a94-4d7f-9911-421bffe17223.png">

See [README.md](https://github.com/MetaMask/test-dapp#deploying)

**Comment by mcmire** [comment]
@psmithson Sorry for the late response on this. You shouldn't need to worry about `bundle.js`. As @katopz stated, this file is generated and uploaded to GitHub Pages when a new version of the dapp is deployed. 

This isn't listed in the README (we need to update it), but you should able to run this dapp locally by saying `yarn start` (then go to `http://localhost:9011`).

Let us know if you have any more issues.
