### ISSUE TITLE
Add Various EIP-712 TypedSign buttons (V1) - part 1 (Blur - Order, PermitBatch, PermitSingle, Seaport - BulkOrder)

### ISSUE THREAD

**Issue by digiwand** [MetaMask/test-dapp#358]
There are various TypedSign structs requested. 

PR: https://github.com/MetaMask/test-dapp/pull/376
- [x] PermitSingle - Uniswap
- [x] PermitBatch - Uniswap
- [x] BulkOrder (Seaport. Seaport OrderComponents exists)
- [x] Order ([example](https://www.notion.so/metamask-consensys/Blur-994115dab74641069218015e76e4d8dc))

See Part 2 issue: https://github.com/MetaMask/test-dapp/issues/377
- [ ] Vote
- [ ] Permit - Dai 
- [ ] PermitWitnessTransferFrom - Uniswap Permit2

**Comment by bschorchit** [comment]
I think we can skip Root since it's only a hex and we won't be able to decode it.
<img width="364" alt="Screenshot 2024-09-23 at 17 56 38" src="https://github.com/user-attachments/assets/fce30413-85de-4ea6-bbf6-6d9d0c4ace9d">

**Comment by digiwand** [comment]
👍🏼  removed Root spec. Thank you @bschorchit!
